name: .NET Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Jackett'
        required: true

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
      
    - name: Dotnet Publish Jackett.Service Windows x64
      run: dotnet publish Jackett.Service -p:Version=${{ github.event.inputs.version }} --sc -r win-x64 -c Release -o ${{env.DOTNET_ROOT}}/Jackett.Windows.x64
    
    - name: Dotnet Publish Jackett.Server Windows x64
      run: dotnet publish Jackett.Server -p:Version=${{ github.event.inputs.version }} -f net6.0 --sc -r win-x64 -c Release -o ${{env.DOTNET_ROOT}}/Jackett.Windows.x64
    
    - name: Dotnet Publish Jackett.Serve Linux x64
      run: dotnet publish Jackett.Server -p:Version=${{ github.event.inputs.version }} -f net6.0 --sc -r linux-x64 -c Release -o ${{env.DOTNET_ROOT}}/Jackett.Linux.x64
    
    - name: Upload Windows x64 Jackett Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Jackett.Binaries.WindowsAMDx64_v${{ github.event.inputs.version }}
        path: ${{env.DOTNET_ROOT}}/Jackett.Windows.x64
        retention-days: 30

    - name: Upload Windows x64 Jackett.Common Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Jackett.Common.Binaries.WindowsAMDx64_v${{ github.event.inputs.version }}
        path: ${{env.DOTNET_ROOT}}/Jackett.Windows.x64/Jackett.Common.*
        retention-days: 30
        
    - name: Upload Linux x64 Jackett Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Jackett.Binaries.LinuxAMDx64_v${{ github.event.inputs.version }}
        path: ${{env.DOTNET_ROOT}}/Jackett.Linux.x64
        retention-days: 30

    - name: Upload Linux x64 Jackett.Common Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Jackett.Common.Binaries.LinuxAMDx64_v${{ github.event.inputs.version }}
        path: ${{env.DOTNET_ROOT}}/Jackett.Linux.x64/Jackett.Common.*
        retention-days: 30